### ISSUE TITLE
[BUG] Server returned Problem (Status: 404) on renew/create

### ISSUE THREAD

**Issue by c-amie** [PKISharp/ACME-PS#100]
**Describe the bug**
v1.1.8 under Server 2019. Went to perform a renewal for all sites with expiring certificates within the next 5 days (5 sites). The first 4 renewed fine. The 5th failed with

Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
At C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.3.0\ACME-PS.psm1:3484 char:13
+             throw [AcmeHttpException]::new($response.ErrorMessage, $r ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
    + FullyQualifiedErrorId : Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization

Updated to v1.3.0, attempted to manually renew the 5th:
Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
At C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.3.0\ACME-PS.psm1:3484 char:13
+             throw [AcmeHttpException]::new($response.ErrorMessage, $r ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
    + FullyQualifiedErrorId : Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization

Jumped over to the LE staging server:
Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
At C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.3.0\ACME-PS.psm1:3484 char:13
+             throw [AcmeHttpException]::new($response.ErrorMessage, $r ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
    + FullyQualifiedErrorId : Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization

Deleted the certificate from the cert store and IIS binding and attempted to create a completely new cert for the same site; single subject name, no SAN's:
Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
At C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.3.0\ACME-PS.psm1:3484 char:13
+             throw [AcmeHttpException]::new($response.ErrorMessage, $r ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
    + FullyQualifiedErrorId : Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization

Deleted the LE cert and binding for a different site on the same server, attempted to create a new cert for it with a single subject name and no SAN's - it worked fine on both LE-staging and LE-production.

**To Reproduce**

**Expected behavior**
The certificate should have renewed as per the other jobs in the batch.

**Additional context (Powershell version, your environment, etc.)**
PS 5.1.17763.1007
v1.3.0
Server 2019 1809   b 17763.1339

Thanks

**Comment by glatzert** [comment]
Is the identifier a wildcard?
Can you get the Authorizations from the order? (Get-Authorization)
Do the look okay? (having two challenges for non-wilcards)
Does the challenge you want to submit look okay?

What state has the order and the authorization before submitting?

**Comment by c-amie** [comment]
Hi glatzert,

These are non-wildcards.

```
Get-ACMEAuthorization -Order $order -State $state
Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
At C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.3.0\ACME-PS.psm1:3484 char:13
+             throw [AcmeHttpException]::new($response.ErrorMessage, $r ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
    + FullyQualifiedErrorId : Server returned Problem (Status: 404).
Type: urn:ietf:params:acme:error:malformed
Expired authorization
```

Looking at the $order
ResourceUrl       : https://acme-v02.api.letsencrypt.org/acme/order/**{8 digit number removed}**/**{10 digit number removed}**
Status            : ready
**Expires           : 2020-05-15T09:32:12Z**
NotBefore         :
NotAfter          :
Identifiers       : {dns:**{correct FQDN removed}**}
AuthorizationUrls : {https://acme-v02.api.letsencrypt.org/acme/authz-v3/**{10 digit number removed}**}
FinalizeUrl       : https://acme-v02.api.letsencrypt.org/acme/finalize/**{8 digit number removed}**/**{10 digit number removed}**
CertificateUrl    :
CSROptions        : AcmeCsrOptions

The expires line is in the past!

**Comment by glatzert** [comment]
Is it okay for your to put your code in a gist?

Also: there's been a bug some time ago, where the module might load an old order from the state, so Removing old files from acme-state\orders might help (order list should also be cleaned - keep the last 5 entries). Find-Order will probably not work after this.

**Comment by c-amie** [comment]
The last 5 (bottom 5 entries) in OrderList.txt happens to include the domain name that I'm trying to renew here.

I removed that line and deleted the related file system data from the Orders folder (dated 8th May 2020) and it has worked as a new creation from scratch.

Thanks for your super-prompt help here. What do you think has happened?

Cheers,

**Comment by glatzert** [comment]
I never got around to really debug it, but essentially it has been a problem with the hash generation.
If you update the module that should already fix it, since the hash is calculated in another way, might it be you did not restart the powershell session after Update-Module?

Else I gonna need to rummage around the state-keeping code to see, what happens there...

**Comment by c-amie** [comment]
You are correct in that I did not restart the PS session, but I did re-exec. Import-Module and Get-Module confirmed it was changed to 1.3.0 from 1.1.8. If that isn't enough, then you are probably correct.

**Comment by glatzert** [comment]
There might still be problems with reloading the classes (PS Modules are not very good at unloading classes).
On occassion, I'll take a closer look into the state mechanics..
