### ISSUE TITLE
[BUG] Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACME-PS#104]
**Describe the bug**
The server running ACME-PS has just had all versions of TLS disabled, except TLS 1.2.

The resulting error from a "Invoke-WebRequest" call (via ACME-PS) is in the title.

We do plenty of WCF communications using TLS 1.2 in the same app that wraps ACME-PS, so we know the issue is strictly ACME-PS.

**To Reproduce**

- Set your server to support TLS 1.2 only.

- Run this:

    New-ACMEState      -Path "C:\ProgramData\MyApp\AcmeState"
    Get-ACMEServiceDirectory "C:\ProgramData\MyApp\AcmeState" -ServiceName "LetsEncrypt" -PassThru

- You will see this:

    Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
    At C:\ProgramData\MyApp\ACME-PS\1.1.5\ACME-PS.psm1:3072 char:25
    + ...  $response = Invoke-WebRequest $serviceDirectoryUrl -UseBasicParsing;
    +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
        + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Expected behavior**
We should have seen this instead (from the "Get-ACMEServiceDirectory" statement):

    ResourceUrl : https://acme-v02.api.letsencrypt.org/directory
    NewAccount  : https://acme-v02.api.letsencrypt.org/acme/new-acct
    NewAuthz    :
    NewNonce    : https://acme-v02.api.letsencrypt.org/acme/new-nonce
    NewOrder    : https://acme-v02.api.letsencrypt.org/acme/new-order
    KeyChange   : https://acme-v02.api.letsencrypt.org/acme/key-change
    RevokeCert  : https://acme-v02.api.letsencrypt.org/acme/revoke-cert
    Meta        : AcmeDirectoryMeta

**Additional context (Powershell version, your environment, etc.)**
The application is running on Windows Server 2016 with .Net 4.8 and PS 5.1 .

Clearly, this is a known PS issue (see [https://bit.ly/2SCYoxT](https://bit.ly/2SCYoxT)).

Perhaps you can come up with an elegant workaround.

I hope you and yours are staying safe Thomas.

**Comment by glatzert** [comment]
Hey George,

I hope you are being well - we are well an safe here in Mainz 👍 

By any chance, did you follow the advice from one of the answers?
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

If you run that before the Script (or Invoke-WebRequest to be more precise), that should configure the .NET Environment used by PowerShell to be able to use TLS1.2 - if that works, we at least would have a viable workaround.

**Comment by glatzert** [comment]
Also, I remembered NuGet deprecating TLS 1.0 and 1.1, which made them write this:
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

There are the necessary reg keys and queries to check for TLS support.
Might it be PS is running in 32 BIT and not having the TLS support set there?

**Comment by GeorgeSchiro** [comment]
We have not implemented the "::Tls12"  workaround as of yet, but we will - as needed.

Here's what's a bit disconcerting (from your 2nd link):

    .NET apps
    If you interact with our APIs using your own app, 
    consider upgrading to .NET Core or .NET Framework 4.7.2 
    or higher. This will ensure that your app defaults to 
    using your operating system’s default TLS version. 
    Alternatively, you can also set your TLS settings using 
    ServicePointManager.SecurityProtocol:

        ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

    Take note that your app will ignore your operating 
    system’s TLS settings if you set 
    ServicePointManager.SecurityProtocol directly. If you 
    explicitly disable TLS 1.2, your app will not use it. 
    It is recommended that you do not set 
    ServicePointManager.SecurityProtocol unless you cannot 
    upgrade your .NET version.

For this reason, we'd prefer not to explicitly set "ServicePointManager.SecurityProtocol" ourselves, especially since we've explicitely complied our code to the .Net 4.8 standard. We would hate to lock-in TLS 1.2 (or whatever version works in the current instance). Naturally, we would prefer to have a single version of AMCE-PS that simply works in whatever environment (which is how PS should work, when not otherwise defective).

That's the reason for the OP. That said, we will do whatever works.

Within ACME-PS, can you possibly detect the availability of only one protocol and set "::Tls12" therein?

**Comment by glatzert** [comment]
I'll take a look from a Windows 2016 machine (I think I have some available), but essentially, setting the OS correctly should do the trick for Powershell as well?

I think doing `[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bOR [Net.SecurityProtocolType]::Tls12` would not lock it in - but I have to take a look at a win 2016 machine for that (I think I have access to some)

**Comment by glatzert** [comment]
I took an Windows 2012R2 and did the following:

```
PS C:\Users\me> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Users\me> [System.Reflection.Assembly]::LoadWithPartialName("System.Net.Http")
PS C:\Users\me> $hc =[System.Net.Http.HttpClient]::new();
PS C:\Users\me> $hm = [System.Net.Http.HttpRequestMessage]::new("GET","https://acme-v02.api.letsencrypt.org")
PS C:\Users\me> $response = $hc.SendAsync($hm).GetAwaiter().GetResult()
PS C:\Users\me> $response


Version             : 1.1
Content             : System.Net.Http.StreamContent
[...]
StatusCode          : OK
IsSuccessStatusCode : True
```

This replicates the code used in ACME-PS to connect to a server and it works.
Thus I think something in your environment might not be configured corretly to satisfy PowerShell.

**Comment by GeorgeSchiro** [comment]
To be sure I fully understand you Thomas, did you fully disable everything related to transport protocols except TLS 1.2 on your 2012R2 server? If so, can you please share the script you used?

**Comment by glatzert** [comment]
No... I was on the wrong track. I thougt, we disabled TLS as well as SSL3 and older, but we did not.
Nevertheless, can you run my code above on your machine?
Also - are you sure, you can connect to letsencrypt from that machine at all?

**Comment by GeorgeSchiro** [comment]
I did. It works on a server that has not had prior versions of TLS disabled. It fails on the server with only TLS 1.2 enabled

Here are the registry changes we applied to disable everything but TLS 1.2:

    Windows Registry Editor Version 5.00

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
    "Enabled"=dword:00000000
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
    "Enabled"=dword:00000000
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
    "Enabled"=dword:00000000
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
    "Enabled"=dword:00000000
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman]
    "ServerMinKeyBitLength"=dword:00000800

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128]
    "Enabled"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128]
    "Enabled"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128]
    "Enabled"=dword:00000000

Can you apply the above changes to your 2012R2 server and run your code again?

**Comment by GeorgeSchiro** [comment]
FYI, here's the version that enables everything (including TLS 1.2):

    Windows Registry Editor Version 5.00

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
    "Enabled"=dword:00000001
    "DisabledByDefault"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
    "DisabledByDefault"=dword:00000000

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman]
    "ServerMinKeyBitLength"=dword:00000800

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128]
    "Enabled"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128]
    "Enabled"=dword:00000001

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128]
    "Enabled"=dword:00000001

Everything works only when everything is enabled (ie. like the above).

**Comment by glatzert** [comment]
Further question: does a "normal" Browser open lets-encrypt on that machine?

**Comment by GeorgeSchiro** [comment]
Yes, both IE and Chrome can get to:

    https://acme-v02.api.letsencrypt.org

even when this fails:

    [System.Net.Http.HttpRequestMessage]::new("GET","https://acme-v02.api.letsencrypt.org")

**Comment by GeorgeSchiro** [comment]
We've determined this is the registry key needed:

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
    "Enabled"=dword:00000001

So apparently PS will attempt to use the TLS 1.0 client provider even though TLS 1.2 has been enabled.

**Comment by glatzert** [comment]
Hey George,
can you check the value of `[System.Net.ServicePointManager]::SecurityProtocol` in your PS

**Comment by glatzert** [comment]
Okay. appearantly PS5 is not build against .Net 4.8 and will need to be configured accordingly, to use the correct protocols.

I'll probably be able to use the same solution as PowerShellGet did, but essentially they set the SecurityProtocol and reset after getting the response. So as a workaround, please set the SecurityProtocol via 
`[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol - bOR [System.Net.SecurityProtocolType]::Tls11 -bOR [System.Net.SecurityProtocolType]::Tls12`

The other solution is to move to PS7 - it does not have this problem.

**Comment by glatzert** [comment]
Also you can try setting `[System.Net.ServicePointManager]::SecurityProtocol = 0` which means "SystemDefault", but I'm not sure, PS5 will support this setting.

**Comment by GeorgeSchiro** [comment]
We'd prefer to have the workaround implemented as transparently as possible Thomas.

So where in your code can you recommend we place something like this:

    $SChannel = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols" 
    $TLS10Client = get-ItemProperty -Path "$($SChannel)\TLS 1.0\Client" -ErrorAction SilentlyContinue
    $TLS10Server = get-ItemProperty -Path "$($SChannel)\TLS 1.0\Server" -ErrorAction SilentlyContinue
    $TLS11Client = get-ItemProperty -Path "$($SChannel)\TLS 1.1\Client" -ErrorAction SilentlyContinue
    $TLS11Server = get-ItemProperty -Path "$($SChannel)\TLS 1.1\Server" -ErrorAction SilentlyContinue
    $TLS12Client = get-ItemProperty -Path "$($SChannel)\TLS 1.2\Client" -ErrorAction SilentlyContinue
    $TLS12Server = get-ItemProperty -Path "$($SChannel)\TLS 1.2\Server" -ErrorAction SilentlyContinue

    if (      $TLS12Client.Enabled `
        -and  $TLS12Server.Enabled `
        -and !$TLS10Client.Enabled `
        -and !$TLS10Server.Enabled `
        -and !$TLS11Client.Enabled `
        -and !$TLS11Server.Enabled `
        )
    {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    }

**Comment by glatzert** [comment]
Hi George,
essentially we need to wrap the HTTPClient Calls (there's one in the code base in Invoke-AcmeWebRequest).
Nevertheless checking for TLS 1.x\Server is not necessary and also the adjustiments should only be made, when [Net.SecurityPointManager]::SecurityProtocol -ne 0 (If it's 0, the value means "SystemDefault").
Additionally it's safe to just enable TLS12.

I'll take a look into the PackageManager Code (probably until wednesday) and add the appropiate code to alliviate your situation :)

**Comment by glatzert** [comment]
1.3.2 beta now exists, please check, if this works for you.

**Comment by GeorgeSchiro** [comment]
The issue actually seems to be with the "Invoke-WebRequest" statement of "ACME-PS/functions/ServiceDirectory/Get-ServiceDirectory.ps1" since that gets hit first.

**Comment by glatzert** [comment]
You're right - I added the workaround there also.
It's two locations where communications appear ;)


1.3.2 beta2 should be available by now.

**Comment by GeorgeSchiro** [comment]
No good:

    Get-ACMEServiceDirectory "C:\ProgramData\GetCert2 - Copy\AcmeState" -ServiceName "LetsEncrypt-Staging" -PassThru
    AcmeDiskPersistedState
    ResourceUrl : https://acme-staging-v02.api.letsencrypt.org/directory
    NewAccount  : https://acme-staging-v02.api.letsencrypt.org/acme/new-acct
    NewAuthz    : 
    NewNonce    : https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce
    NewOrder    : https://acme-staging-v02.api.letsencrypt.org/acme/new-order
    KeyChange   : https://acme-staging-v02.api.letsencrypt.org/acme/key-change
    RevokeCert  : https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert
    Meta        : AcmeDirectoryMeta
    Get-ACMEServiceDirectory : Exception setting "SecurityProtocol": "Cannot convert null to type 
    "System.Net.SecurityProtocolType" due to enumeration values that are not valid. Specify one of the following 
    enumeration values and try again. The possible enumeration values are "SystemDefault,Ssl3,Tls,Tls11,Tls12,Tls13"."
    At C:\ProgramData\GetCert2 - Copy\PowerScript.ps1:4 char:1
    + Get-ACMEServiceDirectory "C:\ProgramData\GetCert2 - Copy\AcmeState" - ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Get-ACMEServiceDirectory], SetValueInvocationException
        + FullyQualifiedErrorId : ExceptionWhenSetting,Get-ACMEServiceDirectory

So I tried doing the most basic barebones test, just to see what happens.

I know you want to preserve then restore the previous state with this Thomas:

    $script:SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol;

But I just want to see what works. So, in each place where you have the above (et al), I tested this instead:

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;

That get's me through the original "Get-ACMEServiceDirectory" error, but then it craps out on "New-ACMEOrder" in the very next stage.

Then I tried various related gyrations - all to no avail.

So this is what appears to be the case:

- Changing "[Net.ServicePointManager]::SecurityProtocol" inside your functions don't seem to work.
- Applying exactly the same change outside your functions works.

Go figure!

**Comment by glatzert** [comment]
Well, I produced a small issue - beta3 should do better (I cannot test it currently, since the machine I used is a production machine)

**Comment by GeorgeSchiro** [comment]
Perhaps I misunderstood Thomas, but I don't see anything new in the repo to test.

**Comment by glatzert** [comment]
I published it as 1.3.2-beta to PSG, but it does not seem to show up there.
It's now also uploaded here.

**Comment by GeorgeSchiro** [comment]
If you meant to publish an updated "dist/ACME-PS/ACME-PS.psm1", I don't see it Thomas. Perhaps I am looking in the wrong place.

**Comment by glatzert** [comment]
Errr.. look again! (No I did not not push it!!11!)

**Comment by GeorgeSchiro** [comment]
Still no good Thomas. "Get-ACMEServiceDirectory" ran NP this time. But now "New-ACMEOrder" locks up with no feedback of any kind (ie. our sub-process call to PS times-out after 5 minutes).

Perhaps it makes sense at this point for you to revert your code until you can reproduce the issue yourself. Until then - and although we still believe the ideal fix is within ACME-PS - we can live with prefixing all our calls to ACME-PS with this:

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;

**Comment by glatzert** [comment]
On another note:
A deadlock of `New-ACMEOrder` (or `Invoke-ACMEWebRequest` to be specific) MIGHT be a problem with asynchronous code as well. I have no idea, how the HttpClient code therein would handle a multithreaded environment ...

**Comment by glatzert** [comment]
I was more referring to "async/await" than to concurrent requests.
But I'm wondering, what `new Process()` will do to an powershell session (we used Exchange Powershell Remoting via System.Automation in a project some time ago)

**Comment by GeorgeSchiro** [comment]
It's purely synchronous.

**Comment by glatzert** [comment]
I'll see, if I can get an Windows 2016 Server from my company to play around and see whatever black magic is happening..

**Comment by GeorgeSchiro** [comment]
Thank you anyway for all your efforts Thomas. It's sad and tiring how often we have to workaround old MS flaws rather than working on new problems of our own.

**Comment by glatzert** [comment]
While digging I found this:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001
```

It's defined here: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls
And it all seems to be a rather big mess.

I'm yet to find out, which .NET Version Powershell 5 is targeting.

**Comment by glatzert** [comment]
> Thank you anyway for all your efforts Thomas. It's sad and tiring how often we have to workaround old MS flaws rather than working on new problems of our own.

You're welcome
