### ISSUE TITLE
[Improvement] Allow export Certificates with alternate chain

### ISSUE THREAD

**Issue by glatzert** [PKISharp/ACME-PS#107]
Switch of the trust chain (LE will do so 21 of Jan), might break some users of LE-certificates, so we need to support the alternate chains.

**Comment by carl4os** [comment]
So LE has made this change and we can no longer use ACME-PS to create staging certs and bind them to Azure. We get an 'unable to upload expired certificate' error when we call `New-AzWebAppSSLBinding`. Do you have plans to support alternate chains soon? LE has mentioned that they have plans to change the default in their [production environment eventually](https://community.letsencrypt.org/t/staging-doctored-durian-root-ca-x3-is-expired-breaks-test-environment/145689/24).

**Comment by glatzert** [comment]
Yes, I started looking into it last year already.
If you happen to know the headers where they present the alternate names, I could implement it right away.

Am 12.03.2021 01:53 schrieb carl4os ***@***.***>:

So LE has made this change and we can no longer use ACME-PS to create staging certs and bind them to Azure. We get an 'unable to upload expired certificate' error when we call New-AzWebAppSSLBinding. Do you have plans to support alternate chains soon? LE has mentioned that they have plans to change the default in their production environment eventually<https://community.letsencrypt.org/t/staging-doctored-durian-root-ca-x3-is-expired-breaks-test-environment/145689/24>.

**Comment by glatzert** [comment]
@carl4os I implemented it, but have currently not the means to test it properly (I hope, I can solve THAT issue in some weeks).
You can download the module files here:  https://github.com/PKISharp/ACME-PS/tree/alternate-chains/dist/ACME-PS
Export-ACMECertificate now has `-UseAlternateChain`

**Comment by carl4os** [comment]
@glatzert Thanks for the quick response and implementation. I'm using the `-UseAlternateChain` parameter now however Azure still returns the same 'Expired certificate is not allowed' error. The certification chain doesn't change on the resulting certificate - I'm seeing the same expired root `Doctored Durian Root CA X3` in certs generated with and without the alternate chain.

**Comment by glatzert** [comment]
`Doctored Durian Root CA X3` what's that? Should it not be `ISRG Root X1` or `X2` or `R3`

**Comment by carl4os** [comment]
Yes, the chains for staging should be as follows per their documentation:

`The Staging API should now serve a default chain of EE <-- R3 <-- X1 <-- DST3 (expired) and alternate chain of EE <-- R3 <-- X1`
[
![image](https://user-images.githubusercontent.com/3272263/111181891-a61f5c00-856b-11eb-8950-1e27fdba1d4e.png)
](url)

All I'm seeing is the first chain though, regardless of the flag. Thanks for looking into this.

**Comment by glatzert** [comment]
It's implemented, and will be available with the next version (1.3.5 or 1.4.1 depending on what the Gallery allows).
I tested it on my local environment and it works well.

To use it call `Export-ACMECertificate -UseAlternateChain`

**Comment by carl4os** [comment]
I've downloaded the newest version to try `-UseAlternateChain`, but I'm getting the same results with and without the flag. In both cases, I'm getting X3 -> X1 -> R3 ->EE. Am I missing something?

**Comment by glatzert** [comment]
Essentially the module loads either one.
I specifically compared the download sizes (use -Verbose to get the link and Invoke-AcmeWebRequest to get the contents), which are different.
IIRC the pfx size will also differ of you save both.
So I assume, you are comparing with windows certificate viewer, which might use additional sources besides the file.

I'll specifically dissect them with OPENSSL tomorrow to get some sense out of it...

**Comment by carl4os** [comment]
Yes, I was comparing them with windows certificate viewer. The issue I'm running into is trying to bind these certs to a custom cname on an azure api app using `New-AzWebAppSSLBinding` which gives me a 'BadRequest' error for these certs. Thanks

**Comment by webprofusion-chrisc** [comment]
A common issue with preferred chain techniques is that in the case of the Let's Encrypt chain you could get the same issuer in both chains, one as the root issuer and one as the second issuer (issued by the expired X3 root as part of their android compatibility fix). Azure needs a trusted root (so not a staging cert) and I believe it won't accept an expired root either, so you do need the chain that starts with ISRG Root X1. Note that if you have an immediate requirement for a working cert and this chain issue is getting in the way you could just use BuyPass Go as your CA (or Zero SSL) as your ACME CA.

**Comment by glatzert** [comment]
> Yes, I was comparing them with windows certificate viewer. The issue I'm running into is trying to bind these certs to a custom cname on an azure api app using `New-AzWebAppSSLBinding` which gives me a 'BadRequest' error for these certs. Thanks

Please be aware, that the module will _default to the Staging Environment_ in Get-AcmeServiceDirectory.
To get valid certificates, use `get-help Get-AcmeServiceDirectory -Full` and look at Example 2.

**Comment by carl4os** [comment]
I understand, thank you. However, prior to the change by expired X3 root change by Let's Encrypt, binding the staging certs to Azure worked. We were doing that in our development environment so that we didn't run into cert generation limits during testing. Now, with the expired root for the cert, we're not able to bind any LE staging cert to Azure. I believe the alternate chain would allow us to bind the staging certs again.

**Comment by glatzert** [comment]
If you read the certificate with OpenSSL, you'll see, it's as expected - so the alternate chain works correctly from a technical viewpoint.
You'll probably need to contact microsoft to sort out, what's going on specifically on Azure.
