### ISSUE TITLE
Improvement: Throw an exception when attempting to get a HTTP-01 challenge for a wildcard order (Get-ACMEChallenge)

### ISSUE THREAD

**Issue by ejpo** [PKISharp/ACME-PS#109]
This was somewhat addressed in issue 87 (https://github.com/PKISharp/ACME-PS/issues/87), but I think it would be nice to give the user some meaningful feedback in this specific scenario.

No exception is thrown when using attempting to get a challenge for a wildcard certificate using a HTTP-01 challenge.
As there is no sample for a DNS certificate, I think it would be useful to throw an exception stating that as per the API, you cannot create a HTTP challenge when trying to request a  wildcard cert.

At the moment, the call to Get-ACMEChallenge just returns nothing and that results in portions of the sample for fulfilling the ACME challenge just bombing out in a stack of errors with no information to help the user to get to the correct solution.

**Comment by glatzert** [comment]
Hi there, that's a good idea, will do (or do you want to? I take PRs)

Also if you happen to have something which creates a DNS-Record, im happy to include it into the samples.

**Comment by ejpo** [comment]
Hey Glatzert,

I was working on some PoSh that would automatically create DNS Records for domains hosted Azure as thats where most of our clients domains live, but I have inevitably been pulled onto 15 other tasks at the moment. Is something this domain specific a good fit for your samples or should it be something that creates DNS records using the DnsServer module to create DNS records using the Windows Server DNS role? 

I must admit, I have not taken a look at the implementation of this module as of yet, but when my brain does return here, I am happy to open a PR implementing this improvement all though I am not sure when on a timeline to push something your way.

**Comment by glatzert** [comment]
Hi ejpo,

I implemented the improvement - that was done quickly :)
(Not yet deployed to PSG, but it'll be part of 1.3.3)

If you have samples, I'm happy to integrate them - even if it's something more specific (currently there's a whole azure runbook for example) - the more samples the better for starters.

**Comment by glatzert** [comment]
Included from 1.3.3
