### ISSUE TITLE
[BUG]? Full chain export seems to be exporting in the wrong order

### ISSUE THREAD

**Issue by anthonysomerset** [PKISharp/ACME-PS#120]
**Describe the bug**
when exporting the certs with none of the special flags around chains
```
$certificateExportPath = $pfxfile
$password = ConvertTo-SecureString -String $CertificatePassword -Force -AsPlainText

Export-ACMECertificate -State $state -Order $order -CertificateKey $certKey -Path $certificateExportPath -Password $password
```

it appears that the chain is being exported in the wrong order - for example normal path should be
 cert < Intermediate (r3) < root (ISRG Root X1)

however it seems to be coming out as
cert < root (ISRG Root X1) < Intermediate (r3) 

while most clients are not complaining - qualys warns of an out of order chain and some Java based clients appear to fail entirely when they encounter this out of order chain

example cert with issue - https://www.sslshopper.com/ssl-checker.html#hostname=myliquid.tech (as at 9th June 2021)
![image](https://user-images.githubusercontent.com/340584/121300495-32d18000-c8f7-11eb-9ef0-bf54fe335c07.png)

**Expected Outcome**
it would be great if the export could have the option to only include the intermediate cert (aka R3 in this case) rather than the root or at least to better detect and export in the correct order (#57 - seems to suggest in some cases the certs import into the pfx file in wrong order?)

**Environment**
for context i am running ACME-PS inside of Azure Automation Accounts (v1.5.0 of ACME-PS) which appears by all appearances to be "Windows PowerShell"

**Comment by glatzert** [comment]
Hi there,

we are using the module on a lot of IIS servers with "Central Certificate Store" and have not seen that behaviour, yet.
So some questions to narrow the problem down:

1) Does your server deliver a chain if you use `-ExcludeChain` (that switch will ignore the chain, that's now included from LE) - the question targets the probability of the chain being explicitly merged by your nginx
2) Can you analyze the certificate with openSSL? (What does it tell about the chain?)
3) Does nginx use PFX, Windows cert store or PEM?

If you want, you can also submit the PUBLIC Key here, so we can take a look at the raw file.

**Comment by anthonysomerset** [comment]
Hi Thanks for feedback, some additional context that was missing on the flow here which will answer question 3 first

1) Azure Automation account that does the LetsEncrypt Renewal, saves the cert to a PFX and then uploads to an Azure KeyVault (no modifications of what comes out of ACME-PS portion of code)
2) Azure App Gateway periodically polls and updates its SSL config when it sees new version of the SSL cert in the KeyVault
3) Nginx is in the backend but does no HTTPS here - the SSL offload is entirely on Azure App Gateway but the downstream server header being passed through at this stage

We had previous issues with AppGateway v2 that if we don't provide any of the chain in the PFX file it would cause errors (HTTP 502) that are well documented on the MSFT side

If i manually edit the PFX file to remove the root cert leaving only the cert and intermediate - everything works OK, which i did as a hot fix for one of the domains - I have yet to try and manually build the PFX or import/export from Windows to see if that changes the ordering correctly and behaves correctly

if i analyze in OpenSSL: `openssl pkcs12 -info -in cert.pfx`

then it presents to me in following order:
Private Key
Root Cert
Intermediate Cert
Cert

which looks correct to me also (unless theres a different command that might highlight something else?)

**Comment by glatzert** [comment]
You can also take the -ExcludeChain switch and append own certificates with the -AdditionalCerts (i think I named it that way) switch, if you want to modify the chain before pfx creation.

Nevertheless - the problem seems to be somewhere else, since I have an url using 1.5.0 which issued a new certificate just this week and it reports the correct order (https://www.sslshopper.com/ssl-checker.html#hostname=researchelements.uni-mainz.de)
