### ISSUE TITLE
Implement Revoke-Certificate

### ISSUE THREAD

**Issue by glatzert** [PKISharp/ACME-PS#13]
Certificate revocation is not yet implemented.
The CertKey Interface needs to be extended to have `Sign(...)` and `ExportJwsPublicKey(…)`

**Comment by glatzert** [comment]
Implemented via #52

**Comment by GeorgeSchiro** [comment]
Merry Xmas Thomas! I hope you and yours are still pleasantly uninfected.

Please let me know the status of "certificate revocation" in ACME-PS. If available, any doco to go with it?

**Comment by glatzert** [comment]
Hey George, the pandemic has been soft with us - mostly isolated, but happy. I hope you're doing well as well.

The certificate revocation is implemented via "Revoke-ACMECertificiate" and currently needs the order, containing the certificate (this should be default since some time). I could also add an implementation for Revoke-Certificate taking the Certificate itself.

**Comment by glatzert** [comment]
Oh and to be fair. It's wildly untested ;)

**Comment by GeorgeSchiro** [comment]
We're still among the living! (in this currently wackadoo - hopefully soon to be more normal - area of the world :o)

Please do add an implementation to revoke given the certificate itself. Clearly you must be given the private key. In what form? PFX file?

Do what you can and we will test it Thomas.

**Comment by glatzert** [comment]
Tracked in #108
