### ISSUE TITLE
Are SHA-1 self signatures being used to issue CSRs? 

### ISSUE THREAD

**Issue by EnronJones** [PKISharp/ACME-PS#130]
LetsEncrypt is planning to stop accepting CSRs that use SHA-1 and are self-signed.  Will this affect ACME-PS?  If so which versions?

https://community.letsencrypt.org/t/rejecting-sha-1-csrs-and-validation-using-tls-1-0-1-1-urls/175144

Thanks,
Arron

**Comment by glatzert** [comment]
The module supports SHA-256, SHA-384 and SHA-512, which are all variants of SHA2.
So SHA-1 deprecation will not affect ACME-PS, since it's not supported in ACME-PS.
