### ISSUE TITLE
[BUG] The certificate chain seems to be out of order in 1.5.2. Versions 1.5.3-beta, and 1.5.4 Fails to run.

### ISSUE THREAD

**Issue by mdande** [PKISharp/ACME-PS#134]
The certificates being generated from the ACME-PS module has the certificates in the wrong order.
Certificate chain

openssl s_client -connect <url:443>

 0 s:/CN=<our cert>
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
 2 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1

From  SSLabs.com 
Additional Certificates (if supplied)
--
Certificates provided | 3 (3963 bytes)
Chain issues | Incorrect order

 uses: azure/powershell@v1
  which uses the latest powershell.

**Comment by glatzert** [comment]
Hi - I probably forgot to push the 1.5.3 version from "beta" to "available".
I'll do that as soon as I'm back on my machine.

**Comment by mdande** [comment]
will that fix the issue?

**Comment by mdande** [comment]
It seems the ACME-PS module 1.5.3-beta and the newer 1.5.4 has not been built with the right source.
 
Here's the stack trace for the error
 
     | Missing an argument for parameter 'First'. Specify a parameter of type

     | 'System.Int32' and try again.
 
at ConvertToCertificateCollection, /home/runner/.local/share/powershell/Modules/ACME-PS/1.5.3/ACME-PS.psm1: line 288

at CreateCertificateCollection, /home/runner/.local/share/powershell/Modules/ACME-PS/1.5.3/ACME-PS.psm1: line 314

at ExportPfxCertificateChain, /home/runner/.local/share/powershell/Modules/ACME-PS/1.5.3/ACME-PS.psm1: line 323

at ExportPfxCertificateChain, /home/runner/.local/share/powershell/Modules/ACME-PS/1.5.3/ACME-PS.psm1: line 318

at Export-Certificate, /home/runner/.local/share/powershell/Modules/ACME-PS/1.5.3/ACME-PS.psm1: line 2275

at <ScriptBlock>, /home/runner/work/plat-apim-core-config/plat-apim-core-config/actions/apim_cert/renew_cert.ps1: line 164

at <ScriptBlock>, /home/runner/work/plat-apim-core-config/plat-apim-core-config/actions/apim_cert/renew_cert.ps1: line 52

at <ScriptBlock>, /home/runner/work/_temp/498d1984-2722-42a5-ab23-521d38535ce8.ps1: line 2

at <ScriptBlock>, <No file>: line 1
 
I downloaded the module psm1 file from 1.5.3-beta and looked at line 288, it clearly says 'select-object -First' and has different source from the GitHub version
 
incorrect code in 1.5.3-beta
 
correct code
https://github.com/PKISharp/ACME-PS/blob/master/ACME-PS/internal/classes/crypto/Certificate.ps1

Currently with the new push of 1.5.4 it has broken our production system and we are pushing out the 1.5.2 which has the incorrect order, but it works.

**Comment by glatzert** [comment]
I added the missing '1' and pushed it as 1.5.6
