### ISSUE TITLE
[BUG] Some of the *ToExport keys are missing from the module manifest

### ISSUE THREAD

**Issue by MartinGC94** [PKISharp/ACME-PS#135]
**Describe the bug**
As a best practice, module manifests should define all of the "ToExport" keys, or at the very least the following keys: "CmdletsToExport", "FunctionsToExport", "AliasesToExport", and the keys should not use wildcards.  
This is because PowerShell analyzes the module manifest first, and if that has been properly defined then it skips the slower analysis. You can see this in the source code here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/AnalysisCache.cs#L126

If you are not exporting any Cmdlets or Aliases then they should be defined as empty array expressions like this: `CmdletsToExport = @()`

**Comment by glatzert** [comment]
That looks like a perfect description of a pull request ... *wink *wink

**Comment by glatzert** [comment]
Thank you very much!
