### ISSUE TITLE
[BUG] v1.5.6 Export-Certificate "value cannot be null"

### ISSUE THREAD

**Issue by seryckd** [PKISharp/ACME-PS#137]
**Describe the bug**
After upgrading to 1.5.6 our workflow started failing with an error on Export-Certificate.

```
Export-ACMECertificate: /home/runner/work/.../renew_cert.ps1:148
Line |
 148 |              Export-ACMECertificate $state -Order $order -CertificateK …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Add" with "1" argument(s): "Value cannot be null.
     | (Parameter 'value')"
```

**To Reproduce**
Call Export-Certificate on a order and export the full chain.

**Expected behavior**
Prior to 1.5.6 the certificate chain was successfully exported (although not in the expected order).

**Additional context (Powershell version, your environment, etc.)**
We traced this to the ConvertToCertificateCollection method in Certificate.ps1. The code to find the root-most certificate is returning null.  It looks like the map contains all the Issuers as keys, so the Where-Object check to see if the Issuer is in the map will always succeed.

When we used the code in this commit the chain was being successfully exported.
https://github.com/PKISharp/ACME-PS/commit/8e9a765b89bc326a9be0b8b5df301df6970d5801

**Comment by glatzert** [comment]
Hm - I'll take another look into the problem.
Do you use LE or is that from another issuer?

**Comment by seryckd** [comment]
We use Let's Encrypt.

**Comment by onikolaiev** [comment]
@glatzert  I faced the same. I did some investigation and found that the CertificateKeyId is empty
![image](https://github.com/PKISharp/ACME-PS/assets/10218336/48ce6759-ee28-4e3a-9273-4558513933fa)
We use  Let's Encrypt as well.

**Comment by msundman78** [comment]
Facing the same problem here using LetsEncrypt or LetEncrypt-Staging. Tested in the following environments, all giving the error with ACME-PS v1.5.6:
Azure Automation Runbook - PS 5.1
Azure Automation Runbook - PS 7.2
Windows 10 - PS 5.1
MacOS 14.1 - PS 7.3.6

**Comment by glatzert** [comment]
Would you folks be so kind and check if 1.5.7-beta fixes the problem AND the chain order?

**Comment by c-amie** [comment]
+1 for this error 1.5.6 has broken my renewals and ability to re-issue new certificates.

`Install-Module -Name ACME-PS -RequiredVersion 1.5.7 -Force  -AllowPrerelease`

Didn't work, complaining that -AllowPrerelease wasn't a valid parameter.

To fix that, I had to run:
```
Install-Module -Name PackageManagement -Repository PSGallery -Force
Install-Module -Name PowerShellGet -Repository PSGallery -Force
```

Which returned:
`PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'ACME-PS'. Try Get-PSRepository to see all available registered module repositories.`

So, dumb question, how are you supposed to install the beta as the above isn't working?

In the end I pulled the nupkg and extracted it to C:\Program Files\WindowsPowerShell\Modules\ACME-PS\1.5.7 manually, registered it and yes, my script appears to be working again under this beta release.

**Comment by glatzert** [comment]
Can you confirm, if the certificates are in the correct order?

**Comment by c-amie** [comment]
@glatzert I am sorry but I have not observed an ordinal issue either on 1.5.2 or 1.5.7. Our workflow just loops the certificates straight into certificates MMC and deletes the on-disk version. There are no certificate chain or trust issues in MMC.

What are the exact steps that you want me to validate the correct order being established please?

**Comment by glatzert** [comment]
> @glatzert I am sorry but I have not observed an ordinal issue either on 1.5.2 or 1.5.7. Our workflow just loops the certificates straight into certificates MMC and deletes the on-disk version. There are no certificate chain or trust issues in MMC.
> 
> What are the exact steps that you want me to validate the correct order being established please?

I see - thanks anyways - im gonna spin up a machine here and validate it myself.

**Comment by msundman78** [comment]
1.5.7 resolved the issue for me as well. Thanks for your quick support!
