### ISSUE TITLE
IIS and Files without extension, probably a easy solution

### ISSUE THREAD

**Issue by zoTT5301** [PKISharp/ACME-PS#35]
I was looking for a suitable solution to automate the IIS-Configuration to support files (mime-types) without extension. I have found a way to do this with powershell and don't have to config that by GUI but: (for me) the solution in the comments dit not work.
I think that was because there is also a handler configuration change neccessary.

After a lot of reading i found a probably better solution: Place a web.config into the challenge directory.
You can copy it from elsewhere or create ist with Set-Content.
At the end the web-config has do exist next to the challenge file before the Check if the challenge is readable ( Invoke-WebRequest $challenge.Data.AbsoluteUrl)
That works for me (Server2016 / IIS10 )without the need of a GUI

Content of web.config (sorry for the format):
`<?xml version = "1.0" encoding="UTF-8"?>
 <configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension="."  mimeType="text/plain" />
            <mimeMap fileExtension=".*" mimeType="text/plain" />
        </staticContent>
        <handlers>
            <clear />
            <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
        </handlers>
     </system.webServer>
 </configuration>
`

**Comment by glatzert** [comment]
If you want to add it via Powershell, you can probably use something like this:

```
PS C:\> Get-IISConfigSection -SectionPath "system.webServer/staticContent" | Get-IISConfigCollection -CollectionName "mimeMap" | New-IISConfigCollectionElement  -ConfigAttribute @{"fileExtension" = "."; "mimeType" = "text/plain"}
```

I'll test and describe it in the README.md when i could test it on some machine.

**Comment by jcastilloMCP** [comment]
For me worked with: 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".*" mimeType="text/plain" />
            <mimeMap fileExtension="." mimeType="text/plain" />
        </staticContent>
    </system.webServer>
</configuration>
