### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACME-PS#75]
Thomas,

You still have the "Authroization" typo in your readme.

That said, this "issue" is just an excuse to let you know we've been testing V1.1.5 for the past 2 months with no issues and how impressed we are!

You've done excellent work and you should be very proud of it Thomas.

Thank you!

'Geo

Ps. You should also know that we were nonplussed when we learned your tool (a replacement for "ACMESharp" - after ACME v1 was deprecated) contains no DLLs! We were amazed to see your code doing everything the former could - with PS only! It's an unbelievably clean solution which makes our "GetCert2" that much cleaner than its predecessor as a result. Then, on top of all that, your non-hesitant willingness to add session independence (between ACME-PS calls) put our admiration over the top. Kudos my friend. If we can make a donation. please let me know how.

**Comment by glatzert** [comment]
Hi George,

thank you very much!
I'll happily take a donation - perhaps you'd like to send me an email via my (now) public address?

PS: 1.1.6 has been released and is already running in my infrastructure. It allows using the `Invoke-AcmeSignedWebRequest` cmdlet, which could be useful, if you want to query resource-urls directly (e.g. to get specific reasons, why a authZ failed).

PPS: next big thing (not public yet) is building an ACME-compliant server based, which connects to an existing ActiveDirectory Certificate Service, to allow internal certificates to be issued via ACME.

**Comment by GeorgeSchiro** [comment]
Thomas, I'm not sure you received the latest email from me asking for confirmation of your BTC address. Please let me know.


BTW, I think you should post your BTC address right here in case anyone else would like to contribute as well.

**Comment by glatzert** [comment]
It really seems, email providers don't like BTC addresses to be shared via email.

I'm thinking about adding a section in README.md, but I'm not really sure if this is "github acceptable" and "OSS acceptable", so i'm hesitant.
Perhaps I should (at last) finish my plan to build a blog where I can write about lessons learned with this and other projects and include the links for PayPal and BTC there.

Nevertheless, I created both Paypal and a BTC-Wallet:
PayPal: <https://www.paypal.me/TGlatzer>
BitCoin Wallet: bc1qr9cnq29ey3uvkutcdfsfrtf8p4lhp027krpv2u

**Comment by glatzert** [comment]
Meanwhile, i've been approved for github sponsors as well :)

**Comment by glatzert** [comment]
Thanks again @GeorgeSchiro - the Repository now contains sponsor-information
