### ISSUE TITLE
Certificate Key Woes....

### ISSUE THREAD

**Issue by christhefmdev** [PKISharp/ACME-PS#83]
Receiving this error in PowerShell and v1.2.0.  Pervious versions did not have this same error.

"You need to provide a certificate key or enable automatic generation.
At C:\Users\ipointsystemadmin\Documents\WindowsPowerShell\Modules\ACME-PS\1.2.0\ACME-PS.psm1:2714
char:13
+             throw "You need to provide a certificate key or enable au ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You need to pro...tic generation.:String) [], Ru
   ntimeException
    + FullyQualifiedErrorId : You need to provide a certificate key or enable automatic generatio
   n."

**Comment by glatzert** [comment]
Can you post your calling line?

**Comment by glatzert** [comment]
Got it - thanks for reporting. 1.2.1 is on its way _NOW_.
