### ISSUE TITLE
JWS verification error

### ISSUE THREAD

**Issue by haviay** [PKISharp/ACME-PS#86]
in your sample 
after i run this code:
`$authorizations = @(Get-ACMEAuthorization -State $acmeStateDir -Order $order);`
i get error:

Server returned Problem (Status: 400). 
Type: urn:ietf:params:acme:error:malformed 
JWS verification error

Any suggestions?

**Comment by gamlielalon1983** [comment]
i didn׳t upload the latest version i fixed all works amazing later ill
attached and tell me if you have any issues ill help you :)

‫בתאריך יום ב׳, 25 במאי 2020 ב-12:09 מאת ‪haviay‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by glatzert** [comment]
It's probably unhappy with your account, meaning the account used to create the order and the account to read the authorizations might not be equal. Make sure $state points to the same location throughout your script.

**Comment by glatzert** [comment]
@haviay which sample did you use btw?

**Comment by haviay** [comment]
This is my full code
(all taken from here:
https://github.com/PKISharp/ACME-PS/tree/master/samples)
`<# -- Variables -- #>
$createregistration = $FALSE

# This directory should point to your web-server document root.
$documentRoot = "C:\websites\Valoreti\prod\prod_Routing.Valoreti";

# ServiceName (valid names are LetsEncrypt and LetsEncrypt-Staging, use the latter one for testing your scripts).
$acmeServiceName = "LetsEncrypt-Staging";

# Your email addresses, where acme services will send informations.
$contactMailAddresses = @("admin@mydomain.com");

# This directory is used to store your account key and service directory urls as well as orders and related data
$acmeStateDir = "C:\CertsV2\01\pfx\$certname.pfx";


<# -- Script -- #>
Import-Module 'ACME-PS';

if($createregistration -eq $TRUE) {
	# Create the state object - will be saved to disk
	New-ACMEState -Path $acmeStateDir;

	# Load URLs from service directory
	Get-ACMEServiceDirectory -State $acmeStateDir -ServiceName $acmeServiceName;

	# Retrieve the first anti-replay nonce
	New-ACMENonce -State $acmeStateDir;

	# Create an account key and store it to the state
	New-ACMEAccountKey -State $acmeStateDir;

	# Register account key with acme service
	New-ACMEAccount -State $acmeStateDir -EmailAddresses $contactMailAddresses -AcceptTOS;
}
# This dns names will be used as identifier
$dnsIdentifiers = @("www.mydomain.co.il", "aaa.mydomain.com", "bbb.mydomain.com", "mydomain.com"); # Strings will automatically be converted to AcmeIdentifier

# Create a new order 
$order = New-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;

if ($null -ne $order) { # Will fetch the order
    $order = Find-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;
}

# Fetch the authorizations for that order
$authorizations = @(Get-ACMEAuthorization -State $acmeStateDir -Order $order);

foreach($authz in $authorizations) {
    # Select a challenge to fullfill
    $challenge = Get-ACMEChallenge -State $acmeStateDir -Authorization $authZ -Type "http-01";

    # Inspect the challenge data (uncomment, if you want to see the object)
    # Depending on the challenge-type this will include different properties
    # $challenge.Data;

    $chFilename = [System.IO.Path]::Combine($documentRoot, $challenge.Data.RelativeUrl);
    $chDirectory = [System.IO.Path]::GetDirectoryName($chFilename);

    # Ensure the challenge directory exists
    if(-not (Test-Path $chDirectory)) {
        New-Item -Path $chDirectory -ItemType Directory;
    }

    Set-Content -Path $chFilename -Value $challenge.Data.Content -NoNewline;

    do {
        ## Sample content - not needed in production.
        $prompt = "Make sure $($challenge.Data.AbsoluteUrl) is reachable from outside of your network. If yes, type 'y'";
        $promptResult = $PSCmdlet.ShouldContinue($prompt, "URL reachable?");
    } while(-not $promptResult);

    # Signal the ACME server that the challenge is ready
    $challenge | Complete-ACMEChallenge -State $acmeStateDir;
}

# Wait a little bit and update the order, until we see the status 'ready' or 'invalid'
while($order.Status -notin ("ready","invalid")) {
    Start-Sleep -Seconds 10;
    $order | Update-ACMEOrder -State $acmeStateDir -PassThru;
}


# Should the order get invalid, use Get-ACMEAuthorizationError to list error details.
if($order.Status -ieq ("invalid")) {
    $order | Get-ACMEAuthorizationError -State $acmeStateDir;
    throw "Order was invalid";
}

# Complete the order - this will issue a certificate singing request
Complete-ACMEOrder -State $acmeStateDir -Order $order -GenerateCertificateKey;

# Now we wait until the ACME service provides the certificate url
while(-not $order.CertificateUrl) {
    Start-Sleep -Seconds 15
    $order | Update-Order -State $acmeStateDir -PassThru
}

# As soon as the url shows up we can create the PFX
Export-ACMECertificate -State $acmeStateDir -Order $order -Path "$certExportPath.pfx";`

**Comment by glatzert** [comment]
Please use formatting or i'll just close the issue.

**Comment by gamlielalon1983** [comment]
https://github.com/gamlielalon1983/letsencryptazure.git

‫בתאריך יום ב׳, 25 במאי 2020 ב-12:31 מאת ‪Thomas Glatzer‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by glatzert** [comment]
Guys you are confusing me.

**Comment by gamlielalon1983** [comment]
I attached my script my that working to try help him

**Comment by glatzert** [comment]
Your script is for Azure, the script here does not look like azure.

**Comment by haviay** [comment]
@glatzert 
I just formatted my code - sorry about that, i'll be happy to get help for that

@gamlielalon1983 
Your code used for Azure

**Comment by glatzert** [comment]
@haviay I'd assume your script ran multiple times with the $createRegistration set to true - thus making the $order object "detached" to the original accountKey - might that be?

In my environments, I always create a registration by hand and after that the script does not have anything like `New-AcmeState; New-AcmeAccount[Key]` or anything like that inside - that works fine and won't get confusing.

**Comment by glatzert** [comment]
Also there was a problem in the samples:
`if ($null -ne $order) { # Will fetch the order` this `-ne` should be `-eq`

**Comment by haviay** [comment]
@glatzert 
Thanks
What is this piece of code for?

```
do {
        ## Sample content - not needed in production.
        $prompt = "Make sure $($challenge.Data.AbsoluteUrl) is reachable from outside of your network. If yes, type 'y'";
        $promptResult = $PSCmdlet.ShouldContinue($prompt, "URL reachable?");
    } while(-not $promptResult);
```

**Comment by glatzert** [comment]
For interactive runs - so you can try, if the challenge url is reachable in your browser (at the end of the day, lets encrypt does the same for your challenge)

**Comment by haviay** [comment]
because i got an error this code...
Can i  remove that?
```
You cannot call a method on a null-valued expression.
At line:17 char:9
    $promptResult = $PSCmdlet.ShouldContinue($prompt, "URL reacha ...
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by glatzert** [comment]
You can safely remove it - it's just for presentation pursposes.

**Comment by haviay** [comment]
Ok @glatzert  Thank you very much
we are almost there
the script created .well-known at c:\
how can i set the right path?

**Comment by glatzert** [comment]
Oh.. `Path::Combine` (see foreach) will do that, if $realtivePath starts with /.
You can replace it with simple concat ($documentRoot + $relativePath)

**Comment by haviay** [comment]
@glatzert  You are champion
The whole code run successfully!!!
i have 2 questions:
1. where can i find the certificate? can i use this command to install the certificate?
`certutil -importPFX $pfxfile` 
2. if i run the same code at the second time(i need it for renew and add more domains every time)
i get this error:
`.pfx does already exist.`

**Comment by glatzert** [comment]
`Export-ACMECertificate -State $acmeStateDir -Order $order -Path "$certExportPath.pfx";`

It's in `$certExportPath.pfx`, which seems not set in your script, so it's probably your working directory.

**Comment by haviay** [comment]
I changed my code like this:
`Export-ACMECertificate -State $acmeStateDir -Order $order -Path $acmeStateDir;`
but i get the error
```
C:\CertsV2\1\pfx\.pfx does already exist.
At C:\Users\valoreti\Documents\WindowsPowerShell\Modules\ACME-PS\1.2.3\ACME-PS.psm1:2115 char:13
             throw "$Path does already exist."
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (C:\CertsV2\1\pf... already exist.:String) [], RuntimeException
     FullyQualifiedErrorId : C:\CertsV2\1\pfx\.pfx does already exist.

```

**Comment by glatzert** [comment]
Nah - just pick a path for export here. E.g. I'll always use $certFile = "C:\Temp\$($dnsName[0])-$([DateTime]::Now.ToString("yyyy-MM-dd")).pfx"

**Comment by glatzert** [comment]
And by the way: Installing PFX files via PowerShell can be done with `Import-PFXCertificate`

**Comment by glatzert** [comment]
I'll asume, this is done.

**Comment by haviay** [comment]
@glatzert  
You are genius

**Comment by glatzert** [comment]
Well, thank you :)
