### ISSUE TITLE
[BUG] Case sensitivity

### ISSUE THREAD

**Issue by christoph-bach** [PKISharp/ACME-PS#94]
Hi

This is not a bug rather a change request.

We have an ACME server product which expects case sensitive JSON fields like it is documented in https://tools.ietf.org/html/rfc8555

For example in chapter 7.3 Account Management, we expect the fields "contact" and "termsOfServiceAgreed". Your client sends us these fields with an upper case first letter: "Contact" instead of "contact" and "TermsOfServiceAgreed" instead of "termsOfServiceAgreed".

**Expected behavior**
We would expect that you send case sensitive field names as documented in https://tools.ietf.org/html/rfc8555. 

This is not must change but would be good practice because URLs are often case sensitive.

Best regards

**Comment by glatzert** [comment]
That is a bug.

ALL other functions will be nice and use lowercase _except_ the New-Account function 🤔
I'll fix it and release 1.2.5 within the day.

-- OT --
May I ask what the acme-server is called?

**Comment by christoph-bach** [comment]
Hi,

Thanks, that is good news. We have implemented ACME in our product true-Xtender Registration Authority (RA-ACME+) and customers are interested in ACME clients implemented in PowerShell.

Link to our product: https://www.keyon.ch/de/Produkte-Loesungen/Microsoft-PKI/index.php#anchor_de2e011d_Accordion-true-Xtender-Registration-Authority

I am therefore testing your client.

Best regards
Christoph

**Comment by glatzert** [comment]
1.2.5 should fix that bug.
