### ISSUE TITLE
[BUG] Error in Complete-Order.ps1 on line 73 if no CertificateKey parameter is passed 

### ISSUE THREAD

**Issue by christoph-bach** [PKISharp/ACME-PS#96]
**Describe the bug**

Error in the script Complete-Order.ps1 if no CertificateKey parameter is provided and the order does not already contain a certificateKey:

`Complete-ACMEOrder -State $acmeStateDir -Order $order -GenerateCertificateKey;
Complete-ACMEOrder : The variable cannot be validated because the value $null is not a valid value for the CertificateKey variable.`

The error occurs on line 73:

`$CertificateKey = $State.GetOrderCertificateKey($Order);`

**Expected behavior**

My code proposal:

`...
process {
        $ErrorActionPreference = 'Stop';

        if($GenerateCertificateKey) {
            $OrderCertificateKey = $State.GetOrderCertificateKey($Order);

            if($null -eq $OrderCertificateKey) {
                $SaveCertificateKey = $true;
                $OrderCertificateKey = New-CertificateKey -SkipKeyExport -WarningAction 'SilentlyContinue';
            }
        }

		if($CertificateKey -ne $null) {
			$OrderCertificateKey = $CertificateKey
		}
		
		if($null -eq $OrderCertificateKey) {
			throw "You need to provide a certificate key or enable automatic generation.";
		}

        if($SaveCertificateKey) {
            $State.SetOrderCertificateKey($Order, $OrderCertificateKey);
        }

        $dnsNames = $Order.Identifiers | ForEach-Object { $_.Value }
        if($Order.CSROptions -and -not [string]::IsNullOrWhiteSpace($Order.CSROptions.DistinguishedName)) {
            $certDN = $Order.CSROptions.DistinguishedName;
        } else {
            $certDN = "CN=$($Order.Identifiers[0].Value)";
        }

        $csr = $OrderCertificateKey.GenerateCsr($dnsNames, $certDN);
...`

**Comment by glatzert** [comment]
Huh?
Do you have any idea _why_ the bug exists before your change?

**Comment by glatzert** [comment]
Okay - that's a little bit unexpected.  
The parameter does not behave like a normal variable during set. PowerShell "Magic".

Nevertheless Version 1.2.6 is on it's way into the gallery. Thanks for your patch.
