### ISSUE TITLE
Question: Is External Account Binding support planned?

### ISSUE THREAD

**Issue by christoph-bach** [PKISharp/ACME-PS#98]
Hi

I successfully tested HTTP-Challenge validation. But will you also implement "External Account Binding" according to RFC8555 (would be great)?

Best regards
Christoph

**Comment by glatzert** [comment]
Never needed it, but it seems not too hard to do, so i'd go for "yes".

**Comment by christoph-bach** [comment]
Thank you for your answer. We have customers who may need this and would contact you if it becomes urgent.

**Comment by glatzert** [comment]
Hey @christoph-bach , I implemented ExternalAccountBinding in 1.3.0-beta2, so if you could give it a shot, if it's working or not (I do not have any server requiring it), that'd be very appreciated.

**Comment by christoph-bach** [comment]
Hi @glatzert , yes I can do that. How can I get this code?

**Comment by glatzert** [comment]
You just need to allow prereleases:
`Install-Module ACME-PS -AllowPrerelease` that should pull 1.3.0-beta2.
Thanks

Am 03.08.2020 08:29 schrieb christoph-bach <notifications@github.com>:

Hi @glatzert<https://github.com/glatzert> , yes I can do that. How can I get this code?

**Comment by christoph-bach** [comment]
Hi @glatzert 

In my test lab, I have:
`Key ID: txra:agb:HZNf8sWc3Hn5dxcSY2pl
MAC Key: DWqgOyy3JRARRy8Wzvw_XEKAQ...Yo1L0PGXK0`

If I run the following command:

PS C:\ACME_Client\ACME-PS-1.2.4\1.3.0> New-ACMEAccount -State $acmeStateDir -AcceptTOS -EmailAddresses $contactMailAddresses -ExternalAccountKID "txra:agb:HZNf8sWc3Hn5dxcSY2pl" -ExternalAccountAlgorithm HS256 -ExternalAccountMACKey DWqgOyy3JRARRy8Wzv
w_XEKAQ...Yo1L0PGXK0

I get:

`Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. "
At C:\ACME_Client\ACME-PS-1.2.4\1.3.0\ACME-PS.psm1:1240 char:16
+         return [Convert]::FromBase64String($base64);
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException`

Do you expect one or both of the 2 parameters in Base64 format?

How could I download the source code of this version to check by myself?

Your parameters ExternalAccountKID and ExternalAccountMACKey are mandatory. I assume you will make them optional to allow the used without external account binding..

Best regards
Christoph

**Comment by christoph-bach** [comment]
Hi @glatzert 

I have forgotten to thank you implementing this so already, thanks a lot!

I encoded the MAC Base64 and I got a step further.

Now our server raises an exception because he misses a Base64 encoding. He wants to decode the externalAccountBinding:

[:](https://tools.ietf.org/html/rfc8555):
...
       "externalAccountBinding": {
         "protected": **base64url**({
           "alg": "HS256",
           "kid": /* key identifier from CA */,
           "url": "https://example.com/acme/new-account"
         }),
...
Could you Base64-encode the externalAccountBinding before you add it to the JSON structure?

Thanks
Best regards

**Comment by glatzert** [comment]
Err.. yes - I read it like three times and appearantly forgot about it.

Can you elaborate on the MAC-key? Do I need a possibility to accept them non-base64 encoded? If yes, what was the representation of your key?

Thanks for your testing.
I'll prepare a beta3.

Best regards
Thomas

**Comment by christoph-bach** [comment]
You do correctly request a Base64 encoded MAC key parameter (recommended in the RFC). I just would mention it in the help of New-ACMEAccount.

**Comment by glatzert** [comment]
1.3.0-beta4 is ready - i added the forgotten base64url-encodes()

**Comment by christoph-bach** [comment]
Hi @glatzert 

It works, I was able to issue a certificate. Only one thing I realized regarding the MAC:

We encode the MAC to a Base64Url and use the following functions for converting:

       public static string ConvertBase64UrlToBase64(string base64url)
        {
            var base64 = base64url
                .Replace("-", "+")
                .Replace("_", "/");
            if (base64.Length % 4 != 0)
            {
                var padding = new String('=', 4 - base64.Length % 4);
                base64 += padding;
            }
            return base64;
        }

        public static string ConvertToBase64Url(byte[] bytes)
        {
            return System.Convert.ToBase64String(bytes).TrimEnd(BASE64_PADDING).Replace('+', '-').Replace('/', '_');
        }

By using the ConvertBase64UrlToBase64 function with my test value "uJNbJTCdPExrDDsLBXKm-DX-XSaVyTMvumKyGqVOAxE" and passing the result "uJNbJTCdPExrDDsLBXKm+DX+XSaVyTMvumKyGqVOAxE=" to New-ACMEAccount as the MAC parameter, it works.

RFC8555: The MAC key SHOULD be provided in base64url-encoded form, to maximize compatibility between non-ACME provisioning systems and ACME clients.

You could update New-ACMEAccount to accept the MAC parameter as a Base64Url ...

Thanks, Cheers
Christoph

**Comment by glatzert** [comment]
Nice :)

I'll check the base64url compatiblity (which should already be given) and will deploy 1.3.0 stable sometime this evening.

Thanks for your testing.
